/**
 * fetchCharts.js
 * Pulls top tracks per genre from Last.fm, enriches with BPM from
 * GetSongBPM.com, then writes src/data/chartTracks.js.
 *
 * Usage:
 *   npm run fetch-charts
 *
 * Required .env keys:
 *   LASTFM_API_KEY       — https://www.last.fm/api/account/create
 *   GETSONGBPM_API_KEY   — https://getsongbpm.com/api (free, 500 req/month)
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import "dotenv/config";

const __dirname = dirname(fileURLToPath(import.meta.url));

const LASTFM_KEY   = process.env.LASTFM_API_KEY;
const SONGBPM_KEY  = process.env.GETSONGBPM_API_KEY;

const GENRE_TAGS = [
  { id: "dnb",        label: "Drum & Bass", emoji: "🥁", tag: "drum-and-bass",  accentColor: "#1e3a5f" },
  { id: "breakbeat",  label: "Breakbeat",   emoji: "⚡", tag: "breakbeat",       accentColor: "#3b1a0a" },
  { id: "chill",      label: "Chill",       emoji: "😌", tag: "downtempo",       accentColor: "#0d2b1a" },
  { id: "house",      label: "House",       emoji: "🏠", tag: "house",           accentColor: "#1a1035" },
  { id: "electronic", label: "Electronic",  emoji: "🎛️", tag: "electronic",      accentColor: "#2d1b00" },
];

const TRACKS_PER_GENRE = 5;

// ── GetSongBPM ────────────────────────────────────────────────────────────────

async function getBpm(artist, title) {
  const lookup = encodeURIComponent(`${title} ${artist}`);
  const url = `https://api.getsongbpm.com/search/?api_key=${SONGBPM_KEY}&type=both&lookup=${lookup}`;
  const res = await fetch(url);
  const data = await res.json();
  const song = data.search?.[0];
  return song?.tempo ? Math.round(Number(song.tempo)) : null;
}

// ── Last.fm ───────────────────────────────────────────────────────────────────

async function getLastFmTopTracks(tag, limit) {
  const url =
    `https://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks` +
    `&tag=${encodeURIComponent(tag)}&limit=${limit}` +
    `&api_key=${LASTFM_KEY}&format=json`;
  const res = await fetch(url);
  const data = await res.json();
  return data.tracks?.track ?? [];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function searchUrl(service, artist, title) {
  const q = encodeURIComponent(`${artist} ${title}`);
  if (service === "spotify")    return `https://open.spotify.com/search/${q}`;
  if (service === "apple")      return `https://music.apple.com/us/search?term=${q}`;
  if (service === "beatport")   return `https://www.beatport.com/search?q=${q}`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  if (!LASTFM_KEY || !SONGBPM_KEY) {
    console.error(
      "❌  Missing env vars. Copy .env.example → .env and fill in your keys.\n" +
      "    Required: LASTFM_API_KEY, GETSONGBPM_API_KEY"
    );
    process.exit(1);
  }

  const genres = [];

  for (const genre of GENRE_TAGS) {
    console.log(`\n🎵  Last.fm top tracks — ${genre.tag}`);
    const lastfmTracks = await getLastFmTopTracks(genre.tag, TRACKS_PER_GENRE);

    const tracks = [];
    for (const t of lastfmTracks) {
      const artist = t.artist.name;
      const title  = t.name;
      process.stdout.write(`   ↳ ${artist} — ${title} … `);

      const bpm = await getBpm(artist, title);
      console.log(bpm ? `${bpm} BPM` : "BPM not found");

      tracks.push({
        id:           `ct-${genre.id}-${tracks.length + 1}`,
        title,
        artist,
        bpm:          bpm ?? null,
        released:     new Date().getFullYear().toString(),
        vibe:         "",
        beatportUrl:  searchUrl("beatport", artist, title),
        appleMusicUrl: searchUrl("apple",   artist, title),
        spotifyUrl:   searchUrl("spotify",  artist, title),
      });

      // Stay within GetSongBPM rate limits
      await new Promise((r) => setTimeout(r, 300));
    }

    genres.push({ ...genre, tracks });
  }

  const now = new Date().toUTCString();
  const output =
    `// Auto-generated by scripts/fetchCharts.js\n` +
    `// Last updated: ${now}\n` +
    `// Re-run with: npm run fetch-charts\n\n` +
    `export const chartGenres = ${JSON.stringify(genres, null, 2)};\n`;

  const outPath = resolve(__dirname, "../src/data/chartTracks.js");
  writeFileSync(outPath, output);
  console.log(`\n✅  Written to src/data/chartTracks.js`);
  console.log(`    Run 'npm run build' to publish the updated charts.`);
}

main().catch((err) => {
  console.error("❌", err.message);
  process.exit(1);
});
