/**
 * fetchCharts.js
 * Pulls top tracks per genre from Last.fm, then writes src/data/chartTracks.js.
 *
 * Usage:
 *   npm run fetch-charts
 *
 * Required .env keys:
 *   LASTFM_API_KEY  — https://www.last.fm/api/account/create
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import "dotenv/config";

const __dirname = dirname(fileURLToPath(import.meta.url));

const LASTFM_KEY = process.env.LASTFM_API_KEY;

const GENRE_TAGS = [
  { id: "dnb",        label: "Drum & Bass", emoji: "🥁", tag: "drum-and-bass",  accentColor: "#1e3a5f" },
  { id: "breakbeat",  label: "Breakbeat",   emoji: "⚡", tag: "breakbeat",       accentColor: "#3b1a0a" },
  { id: "chill",      label: "Chill",       emoji: "😌", tag: "downtempo",       accentColor: "#0d2b1a" },
  { id: "house",      label: "House",       emoji: "🏠", tag: "house",           accentColor: "#1a1035" },
  { id: "electronic", label: "Electronic",  emoji: "🎛️", tag: "electronic",      accentColor: "#2d1b00" },
];

const TRACKS_PER_GENRE = 5;

async function getLastFmTopTracks(tag, limit) {
  const url =
    `https://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks` +
    `&tag=${encodeURIComponent(tag)}&limit=${limit}` +
    `&api_key=${LASTFM_KEY}&format=json`;
  const res = await fetch(url);
  const data = await res.json();
  return data.tracks?.track ?? [];
}

function searchUrl(service, artist, title) {
  const q = encodeURIComponent(`${artist} ${title}`);
  if (service === "spotify")  return `https://open.spotify.com/search/${q}`;
  if (service === "apple")    return `https://music.apple.com/us/search?term=${q}`;
  if (service === "beatport") return `https://www.beatport.com/search?q=${q}`;
}

async function main() {
  if (!LASTFM_KEY) {
    console.error("❌  Missing LASTFM_API_KEY in .env");
    process.exit(1);
  }

  const genres = [];

  for (const genre of GENRE_TAGS) {
    console.log(`🎵  Fetching Last.fm top tracks — ${genre.tag}`);
    const lastfmTracks = await getLastFmTopTracks(genre.tag, TRACKS_PER_GENRE);

    const tracks = lastfmTracks.map((t, i) => {
      const artist = t.artist.name;
      const title  = t.name;
      console.log(`   ↳ ${artist} — ${title}`);
      return {
        id:           `ct-${genre.id}-${i + 1}`,
        title,
        artist,
        beatportUrl:  searchUrl("beatport", artist, title),
        appleMusicUrl: searchUrl("apple",   artist, title),
        spotifyUrl:   searchUrl("spotify",  artist, title),
      };
    });

    genres.push({ ...genre, tracks });
  }

  const now = new Date().toUTCString();
  const output =
    `// Auto-generated by scripts/fetchCharts.js\n` +
    `// Last updated: ${now}\n` +
    `// Re-run with: npm run fetch-charts\n\n` +
    `export const chartGenres = ${JSON.stringify(genres, null, 2)};\n`;

  writeFileSync(resolve(__dirname, "../src/data/chartTracks.js"), output);
  console.log(`\n✅  Written to src/data/chartTracks.js`);
}

main().catch((err) => {
  console.error("❌", err.message);
  process.exit(1);
});
