export const S = {
  container: { minHeight: '100vh', background: '#0a0a0a', color: '#e5e7eb', fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif", maxWidth: 680, margin: '0 auto', padding: '0 0 60px' },
  header: { padding: '32px 24px 20px', borderBottom: '1px solid #1f2937' },
  logo: { fontSize: 26, fontWeight: 800, letterSpacing: '0.05em', color: '#f97316' },
  subtitle: { fontSize: 12, color: '#6b7280', marginTop: 4, letterSpacing: '0.1em', textTransform: 'uppercase' },
  tabBar: { display: 'flex', borderBottom: '1px solid #1f2937', overflowX: 'auto' },
  tab: { padding: '12px 18px', background: 'none', border: 'none', color: '#6b7280', fontSize: 13, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', borderBottom: '2px solid transparent', position: 'relative' },
  tabActive: { color: '#f97316', borderBottom: '2px solid #f97316' },
  badge: { marginLeft: 6, background: '#f97316', color: '#000', borderRadius: 10, padding: '1px 6px', fontSize: 11, fontWeight: 700 },
  content: { padding: '20px 16px' },
  sectionLabel: { fontSize: 11, fontWeight: 700, color: '#6b7280', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 16, marginTop: 8 },
  card: { background: '#16120e', border: '1px solid #2d1810', borderRadius: 10, padding: '16px', marginBottom: 12 },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 },
  trackTitle: { fontSize: 15, fontWeight: 700, color: '#f9fafb' },
  trackArtist: { fontSize: 13, color: '#8a7a65', marginTop: 2 },
  starBtn: { background: 'none', border: 'none', cursor: 'pointer', padding: 4, lineHeight: 0 },
  duration: { fontSize: 12, color: '#6b7280', whiteSpace: 'nowrap', paddingTop: 2 },
  tags: { display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  tag: { fontSize: 11, fontWeight: 600, background: '#1a1610', color: '#8a7a65', borderRadius: 4, padding: '2px 8px' },
  vibe: { fontSize: 12, color: '#8a7a65', fontStyle: 'italic', marginBottom: 12 },
  btnRow: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  btn: { display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 12, fontWeight: 600, color: '#fff', textDecoration: 'none', padding: '6px 12px', borderRadius: 6 },
  empty: { color: '#7a6a55', fontSize: 14, textAlign: 'center', padding: '40px 0', fontStyle: 'italic' },
  footer: { textAlign: 'center', fontSize: 11, color: '#374151', padding: '24px 16px 0', borderTop: '1px solid #111827' },
  filterBar: { display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 16 },
  filterChip: { fontSize: 12, fontWeight: 600, background: '#1f2937', color: '#6b7280', border: '1px solid #374151', borderRadius: 16, padding: '5px 14px', cursor: 'pointer', transition: 'all 0.15s' },
  filterChipActive: { background: '#f97316', color: '#000', borderColor: '#f97316' },
};

export const genreAccent = {
  dnb: '#1e3a5f',
  breakbeat: '#4a1d6b',
  house: '#1a3d1a',
  electronic: '#3d2e1a',
  chill: '#1a2e3d',
  blues: '#1a1a3d',
};
